### ISSUE TITLE
Attempt to wget the deb per your documentation returns 404 Not Found

### ISSUE THREAD

**Issue by ga900p25** [Wodie/p25link#3]
The step in your documentation does not retrieve the 'deb'.  That is as far as I got.
Thanks,
Ken

sudo wget https://github.com/Wodie/p25link/raw/master/installer/p25link_2.40-8.deb
--2024-09-20 19:48:53--  https://github.com/Wodie/p25link/raw/master/installer/p25link_2.40-8.deb
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-09-20 19:48:53 ERROR 404: Not Found.

I think the URL is incorrect in the instructions.  I cobbled this link together it appeared to retrieve the 'deb' I specified.

Instead of sudo wget https://github.com/Wodie/p25link/raw/master/installer/p25link_2.40-8.deb

I used changed the path substituting 'raw' with 'tree'.  

sudo wget https://github.com/Wodie/p25link/tree/master/installer/p25link_2.40-8.deb

I think this closes the issue.
Thanks.

**Comment by Wodie** [comment]
Hi, I will have a look during the weekend to see what I missed. As no one let me know they downloaded or let me know they are using the code, I was not updating it any more.

Regards,
Juan Carlos

**Comment by ga900p25** [comment]
The path in the instructions may need revision. 

I used this path, substituting 'raw' with 'tree'.  

sudo wget https://github.com/Wodie/p25link/tree/master/installer/p25link_2.40-8.deb

This works.
